openapi: 3.2.0
info:
  title: Student Web Service (SWS) Degree Audit Program API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: DegreeAuditProgram
paths:
  /v5/degreeauditprogram:
    get:
      tags:
      - DegreeAuditProgram
      summary: Search for degree audit programs that match the supplied parameters
      description: '{

        "DisplayTitle" : "Degree Audit Program Search",

        "ews_guid" : "4CD2A808-F00C-4878-B330-442015FB6B6A",

        "LongDescription" : "Search for a list of programs that can be used for a degree audit which can be filtered by

        campus, major and degree group",

        "ShortDescription" : "Search for a list of educational programs",

        "OriginatingSchema" : [ { "source":"sdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        For campus codes see the campus resource.

        The service formats and sends a query string to the Student database. You may search by

        any combination of the campus, major_abbreviation and degree_group parameters.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.degree" ],

        "Synonyms" : []

        }'
      operationId: DegreeAuditProgramSearch
      parameters:
      - name: campus
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: major_abbreviation
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: degree_group
        in: query
        description: GRADUATE, MINOR, UNDERGRADUATE or blank. When nothing is specified for degree_group then all results are returned.
        schema:
          type: string
          default: ''
      responses:
        '400':
          description: 'Invalid arg: campus | Invalid arg: majorAbbreviation | Invalid arg: Degree Group'
        '404':
          description: No degree audit programs found.
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/DegreeAuditProgramSearchViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/DegreeAuditProgramSearchViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/DegreeAuditProgramSearchViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/DegreeAuditProgramSearchViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/DegreeAuditProgramSearchViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/DegreeAuditProgramSearchViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    DegreeAuditProgramSearchResultViewModel:
      type: object
      properties:
        DegreeAuditProgramTitle:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dpg.ttl\" }\n                ],\n                \"TechnicalDescription\": \"Degree Audit Program Title\"\n            }\n            </pre>"
        Campus:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dpg.brcd\" }\n                ],\n                \"TechnicalDescription\": \"Campus\"\n            }\n            </pre>"
        DegreeLevel:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dpg.dlvl\" }\n                ],\n                \"TechnicalDescription\": \"Degree Level\"\n            }\n            </pre>"
        DegreeType:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dpg.dtyp\" }\n                ],\n                \"TechnicalDescription\": \"Degree Type\"\n            }\n            </pre>"
        MajorAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dpg.mabb\" }\n                ],\n                \"TechnicalDescription\": \"Major Abbreivation\"\n            }\n            </pre>"
        Pathway:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dpg.pth\" }\n                ],\n                \"TechnicalDescription\": \"Pathway\"\n            }\n            </pre>"
        regid_placeholder:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"UW Registration ID\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Degree Audit Program Search Result Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.DegreeAuditProgram\"}]\n}"
    DegreeAuditProgramSearchViewModel:
      type: object
      properties:
        TotalCount:
          type: integer
          format: int32
        DegreeAuditPrograms:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DegreeAuditProgramSearchResultViewModel'
          readOnly: true
        Current:
          $ref: '#/components/schemas/DegreeAuditProgramSearchResourceURI'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Degree Audit Program Search Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.DegreeAuditProgram\"}]\n}"
    DegreeAuditProgramSearchResourceURI:
      type: object
      properties:
        Campus:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        MajorAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        DegreeGroup:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Degree Audit Program Search Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.DegreeAuditProgram\"}],\n    \"TargetOperationId\" : [\"DegreeAuditProgramSearch\"]\n}"
