openapi: 3.2.0
info:
  title: Student Web Service (SWS) Program API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: Program
paths:
  /v5/program/{major_abbr},{pathway},{year},{quarter}:
    get:
      tags:
      - Program
      summary: Search for a program of study that matches the parameters
      description: '{

        "DisplayTitle" : "Program",

        "ews_guid" : "0B74F119-61ED-44EF-9B5D-61DDF180B9F6",

        "LongDescription" : "Find the information about a program of study that matches the parameters",

        "ShortDescription" : "Information about a program of study",

        "OriginatingSchema" : [ { "source":"swssdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        - AccessToken

        Program is previously considered major and pathway.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.degreemajor" ],

        "Synonyms" : []

        }'
      operationId: GetProgram
      parameters:
      - name: major_abbr
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: pathway
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: year
        in: path
        description: 'The 4 digit year.  For example: 2025'
        required: true
        schema:
          maxLength: 4
          minLength: 4
          type: string
      - name: quarter
        in: path
        description: 'The 1 digit quarter.  For example: 0=Default, 1=winter, 2=spring, 3=summer, 4=autumn'
        required: true
        schema:
          maxLength: 6
          minLength: 6
          type: string
      responses:
        '400':
          description: 'Invalid arg: year | Invalid arg: quarter'
        '500':
          description: System.FormatException | Program is null or empty. | InternalServerError
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/ProgramViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProgramViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ProgramViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/ProgramViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ProgramViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ProgramViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '503':
          description: ServiceUnavailable
  /v5/program:
    get:
      tags:
      - Program
      summary: Search for programs of study that match the supplied parameters
      description: '{

        "DisplayTitle" : "Program Search",

        "ews_guid" : "8135DEB6-FC3B-4672-B36A-62FB43EE4279",

        "LongDescription" : "Search for a set of programs of study that match the supplied parameters",

        "ShortDescription" : "Search for a list of programs of study",

        "OriginatingSchema" : [ { "source":"swssdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        - AccessToken

        Program is previously considered major and pathway.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.degreemajor" ],

        "Synonyms" : []

        }'
      operationId: ProgramSearch
      parameters:
      - name: year
        in: query
        description: 'The 4 digit year.  For example: 2025'
        required: true
        schema:
          type: string
          default: ''
      - name: quarter
        in: query
        description: 'The 1 digit quarter.  For example: 0=Default, 1=winter, 2=spring, 3=summer, 4=autumn'
        required: true
        schema:
          type: string
          default: ''
      - name: major_abbr
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: pathway
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: page_size
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: page_start
        in: query
        description: ''
        schema:
          type: string
          default: ''
      responses:
        '400':
          description: 'Invalid arg: year | Invalid arg: quarter'
        '500':
          description: System.FormatException | InternalServerError
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/ProgramSearchViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ProgramSearchViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ProgramSearchViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/ProgramSearchViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ProgramSearchViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ProgramSearchViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '503':
          description: ServiceUnavailable
components:
  schemas:
    TermResourceUri:
      type: object
      properties:
        Href:
          type:
          - string
          - 'null'
        Year:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_last_yr\" },\n                    { \"source\":\"SWSSDB.sr_major_code.major_first_yr\" },\n                    { \"source\":\"SWSSDB.sys_tbl_39_calendar.table_key\" },\n                    { \"source\":\"SWSSDB.student_1.last_yr_enrolled\" },\n                    { \"source\":\"SDB.SWI610.trm/yr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_yr\" },\n                    { \"source\":\"UWEO.selSWSRegistrations.FirstEffectiveTerm/Year\"}\n                ],\n                \"TechnicalDescription\": \"Year for the given term\"\n            }\n            </pre>"
          format: int32
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_last_qtr\" },\n                    { \"source\":\"SWSSDB.sr_major_code.major_first_qtr\" },\n                    { \"source\":\"SWSSDB.sys_tbl_39_calendar.table_key\" },\n                    { \"source\":\"SWSSDB.student_1.last_qtr_enrolled\" },\n                    { \"source\":\"SDB.SWI610.trm/qtr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_qtr\" },\n                    { \"source\":\"UWEO.selSWSRegistrations.FirstEffectiveTerm/Quarter\"}\n                ],\n                \"TechnicalDescription\": \"Quarter for the given term\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Term Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Term\"}],\n    \"TargetOperationId\" : [\"GetTerm\"]\n}"
    ProgramResourceUri:
      type: object
      properties:
        Href:
          type:
          - string
          - 'null'
        MajorAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Major Abbreviation\"\n            }\n            </pre>"
        Pathway:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_pathway\" }\n                ],\n                \"TechnicalDescription\": \"Pathway\"\n            }\n            </pre>"
        Year:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_first_yr\" },\n                    { \"source\":\"SWSSDB.sr_major_code.major_last_yr\" }\n                ],\n                \"TechnicalDescription\": \"Year\"\n            }\n            </pre>"
          format: int32
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_first_qtr\" },\n                    { \"source\":\"SWSSDB.sr_major_code.major_last_qtr\" }\n                ],\n                \"TechnicalDescription\": \"Quarter\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Program Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Program\"}],\n    \"TargetOperationId\" : [\"GetProgram\"]\n}"
    ProgramViewModel:
      type: object
      properties:
        ProgramUri:
          $ref: '#/components/schemas/ProgramResourceUri'
        Department:
          $ref: '#/components/schemas/DepartmentViewModel'
        MajorFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"Full name\"\n            }\n            </pre>"
        MajorName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_name\" }\n                ],\n                \"TechnicalDescription\": \"Name\"\n            }\n            </pre>"
        MajorShortName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_short_nm\" }\n                ],\n                \"TechnicalDescription\": \"Short name\"\n            }\n            </pre>"
        Pathway:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_pathway\" }\n                ],\n                \"TechnicalDescription\": \"Pathway\"\n            }\n            </pre>"
        FirstEffectiveTerm:
          $ref: '#/components/schemas/TermResourceUri'
        LastEffectiveTerm:
          $ref: '#/components/schemas/TermResourceUri'
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Program Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Program\"}]\n}"
    ProgramSearchViewModel:
      type: object
      properties:
        Current:
          $ref: '#/components/schemas/ProgramSearchResourceUri'
        Next:
          $ref: '#/components/schemas/ProgramSearchResourceUri'
        Previous:
          $ref: '#/components/schemas/ProgramSearchResourceUri'
        TotalCount:
          type: integer
          format: int32
        Programs:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ProgramViewModel'
          readOnly: true
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Program Search Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Program\"}]\n}"
    DepartmentViewModel:
      type: object
      properties:
        CollegeAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_dept_code.dept_college\" }\n                ],\n                \"TechnicalDescription\": \"College Abbreviation\"\n            }\n            </pre>"
        DepartmentAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_dept_code.dept_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Department Abbreviation\"\n            }\n            </pre>"
        DepartmentFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_dept_code.dept_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"Department Full Name\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Department Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Department\"}]\n}"
    ProgramSearchResourceUri:
      type: object
      properties:
        Year:
          type: integer
          format: int32
        Quarter:
          type:
          - string
          - 'null'
        Pathway:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                   { \"source\":\"SWSSDB.sr_major_code.major_pathway\" }\n                ],\n                \"TechnicalDescription\": \"Pathway\"\n            }\n            </pre>"
        MajorAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                   { \"source\":\"SWSSDB.sr_major_code.major_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Major abbreviation\"\n            }\n            </pre>"
        PageStart:
          type:
          - string
          - 'null'
        PageSize:
          type:
          - string
          - 'null'
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Program Search Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Program\"}],\n    \"TargetOperationId\" : [\"ProgramSearch\"]\n}"
