openapi: 3.2.0
info:
  title: Student Web Service (SWS) Degree Audit Status API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: DegreeAuditStatus
paths:
  /v5/degreeauditstatus/{campus},{majorabbreviation},{pathway},{degreelevel},{degreetype},{regid},{jobid}:
    get:
      tags:
      - DegreeAuditStatus
      summary: Get the specified status of a degree audit request
      description: '{

        "DisplayTitle" : "Degree Audit Status",

        "ews_guid" : "7503B636-AA7A-4145-B326-A90CA48965AE",

        "LongDescription" : "Returns the specified status of a degree audit request",

        "ShortDescription" : "The status of a degree audit request",

        "OriginatingSchema" : [ { "source":"sdb" }, { "source":"irws" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:DegreeAuditSubmitter

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        This resource is associated with a previous degree audit create request. See the degree audit resource.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.degree" ],

        "Synonyms" : []

        }'
      operationId: GetDegreeAuditStatus
      parameters:
      - name: campus
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: majorAbbreviation
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: pathway
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: degreeLevel
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: degreeType
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: regid
        in: path
        description: RegIDs are the authoritative unique IDs guaranteed to identify a UW person permanently.  RegIDs are assigned to a person by the Identity Registration Service, the authoritative source for person data reconciled from several data sources which may represent multiple records and accounts for a single person.  A given RegID will always refer to the same person, regardless of name, status or affiliation changes.
        required: true
        schema:
          type: string
      - name: jobid
        in: path
        description: Every request to create a degree audit generates a jobid.  It is required to identify the status.
        required: true
        schema:
          type: string
      responses:
        '400':
          description: 'Invalid arg: campus | Invalid arg: majorAbbreviation | Invalid arg: pathway | Invalid arg: degreeLevel | Invalid arg: degreeType | Invalid arg: regid | Invalid arg: jobid'
        '404':
          description: CTC Student audit status cannot be retrieved via the SWS DegreeAuditStatus resource. | Term not found
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/DegreeAuditStatusViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/DegreeAuditStatusViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/DegreeAuditStatusViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/DegreeAuditStatusViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/DegreeAuditStatusViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/DegreeAuditStatusViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    DegreeAuditResourceUri:
      type: object
      properties:
        Campus:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dgp/brcd\" }\n                ],\n                \"TechnicalDescription\": \"Campus\"\n            }\n            </pre>"
        DegreeLevel:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dgp/dlvl\" }\n                ],\n                \"TechnicalDescription\": \"Degree Level\"\n            }\n            </pre>"
        DegreeType:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dgp/dtyp\" }\n                ],\n                \"TechnicalDescription\": \"Degree Type\"\n            }\n            </pre>"
        Href:
          type:
          - string
          - 'null'
        MajorAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dgp/mabb\" }\n                ],\n                \"TechnicalDescription\": \"Major Abbreviation\"\n            }\n            </pre>"
        Pathway:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dgp/pth\" }\n                ],\n                \"TechnicalDescription\": \"Pathway\"\n            }\n            </pre>"
        RegID:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI394.dgp/sysk\" }\n                ],\n                \"TechnicalDescription\": \"UW Registration ID\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Degree Audit Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.DegreeAudit\"}],\n    \"TargetOperationId\" : [\"DegreeAuditSearch\"]\n}"
    DegreeAuditStatusViewModel:
      type: object
      properties:
        Title:
          type:
          - string
          - 'null'
        Status:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        DegreeAuditURI:
          $ref: '#/components/schemas/DegreeAuditResourceUri'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Degree Audit Status Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.DegreeAudit\"}]\n}"
