openapi: 3.2.0
info:
  title: Student Web Service (SWS) Notice API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: Notice
paths:
  /v5/notice/{uwregid}:
    get:
      tags:
      - Notice
      summary: Get the notices for the specified student
      description: '{

        "DisplayTitle" : "Notice",

        "ews_guid" : "DBDF33C9-EB9E-4C67-8E71-61477BE427A9",

        "LongDescription" : "Display the notices that should be relevant to the specified student at the time of request.

        (e.g. alert notice, general notice, dates and deadlines notice, checklist item notice)",

        "ShortDescription" : "Notices for a student",

        "OriginatingSchema" : [ { "source":"sdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:NoticeReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID ",

        "Links" : [ "" ],

        "Synonyms" : []

        }'
      operationId: GetNotice
      parameters:
      - name: uwregid
        in: path
        description: RegIDs are the authoritative unique IDs guaranteed to identify a UW person permanently.  RegIDs are assigned to a person by the Identity Registration Service, the authoritative source for person data reconciled from several data sources which may represent multiple records and accounts for a single person.  A given RegID will always refer to the same person, regardless of name, status or affiliation changes.
        required: true
        schema:
          type: string
      responses:
        '400':
          description: 'Invalid arg: regid ID'
        '404':
          description: No notice found.
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/MainNoticeViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/MainNoticeViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/MainNoticeViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/MainNoticeViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/MainNoticeViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/MainNoticeViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    PersonResourceUri:
      type: object
      properties:
        Name:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"IRWS.identity.uwPersonPrefferredName\" },\n                    { \"source\":\"IRWS.identity.uwPersonRegisteredName\" }\n                ],\n                \"TechnicalDescription\": \"This field is resource specific\"\n            }\n            </pre>"
        RegID:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"IRWS.identity.regid\" }\n                ],\n                \"TechnicalDescription\": \"UW Registration ID. This field is resource specific\"\n            }\n            </pre>"
        Pronouns:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"IRWS.identity.uwPersonPronoun\" }\n                ],\n                \"TechnicalDescription\": \"\"\n            }\n            </pre>"
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Person Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Person\"}],\n    \"TargetOperationId\" : [\"GetPerson\"]\n}"
    NoticeAttributeViewModel:
      type: object
      properties:
        Name:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI102.attr.nm\" }\n                ],\n                \"TechnicalDescription\": \"Notice attribute name\"\n            }\n            </pre>"
        DataType:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI102.attr.typ\" }\n                ],\n                \"TechnicalDescription\": \"Data Type\"\n            }\n            </pre>"
        Value:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI102.attr.val\" }\n                ],\n                \"TechnicalDescription\": \"Value\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Notice Attribute Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Notice\"}]\n}"
    NoticeViewModel:
      type: object
      properties:
        NoticeAttributes:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/NoticeAttributeViewModel'
        NoticeCategory:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI102.msg.cat\" }\n                ],\n                \"TechnicalDescription\": \"Notice Category\"\n            }\n            </pre>"
        NoticeContent:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI102.msg.txt\" }\n                ],\n                \"TechnicalDescription\": \"Notice Content\"\n            }\n            </pre>"
        NoticeType:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SDB.SWI102.msg.typ\" }\n                ],\n                \"TechnicalDescription\": \"Notice Type\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Notice Model\"\n}"
    MainNoticeViewModel:
      type: object
      properties:
        Person:
          $ref: '#/components/schemas/PersonResourceUri'
        Notices:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/NoticeViewModel'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Person Notices Model\"\n}"
