openapi: 3.0.1
info:
  title: IdCard Web Service (IdCardWS) Campus ResourceList API
  description: IdCard Web Service (IdCardWS) provides a RESTful API to UW IdCard data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/idcardws-users to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: idcardws-support@uw.edu
  version: v1
servers:
- url: /idcard
tags:
- name: ResourceList
paths:
  /v1:
    get:
      tags:
      - ResourceList
      operationId: GetResources
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
  /v5:
    get:
      tags:
      - ResourceList
      summary: Get available v5 resources
      description: "<pre>\r\n                {\r\n                    \"DisplayTitle\" : \"Service Resource List\",\r\n                    \"ews_guid\" : \"4533A5E5-2C26-4923-8574-A6C07FFFE51D\",\r\n                    \"LongDescription\" : \"Get available resources\",\r\n                    \"ShortDescription\" : \"Get available resources\",\r\n                    \"OriginatingSchema\" : [ { \"source\": \"hardcoded\" } ],\r\n                    \"Notes\" : \"This resource requires any of the following ASTRA roles:\r\n                                 - sws:Support\r\n                                 - sws:GradeSubmitter\r\n                                 - sws:UnitReader\r\n                                 - sws:AdmReader\r\n                               This resource supports the following authentication types:\r\n                                 - X.509 Certificate\r\n                                 - NetID\r\n                                 - AccessToken \",\r\n                    \"Links\" : [],\r\n                    \"Synonyms\" : []\r\n                }\r\n                </pre>"
      operationId: GetSWSResources
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel_2'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel_2'
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel_2'
            text/plain:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel_2'
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel_2'
            text/json:
              schema:
                $ref: '#/components/schemas/ResourceListViewModel_2'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    UriResourceWithTitle:
      type: object
      properties:
        href:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    UriResourceWithTitle_2:
      type: object
      properties:
        Href:
          type: string
          format: uri
          nullable: true
        Name:
          type: string
          nullable: true
      additionalProperties: false
      description: "{\r\n    \"DisplayTitle\" : \"Resource URI\"\r\n}"
    ResourceListViewModel_2:
      type: object
      properties:
        Resources:
          type: array
          items:
            $ref: '#/components/schemas/UriResourceWithTitle_2'
          nullable: true
      additionalProperties: false
      description: "{\r\n    \"DisplayTitle\" : \"Resource List Model\",\r\n    \"TargetSchema\" : [{\"target\" : \"SWS.Resource\"}]\r\n}"
    ViewFormats:
      enum:
      - 1
      - 2
      - 3
      - 5
      type: integer
      format: int32
    ResourceListViewModel:
      type: object
      properties:
        metadata:
          type: string
          nullable: true
        pageCount:
          type: string
          description: "Actual number of records on the current search results page. This must be set by the view in order\r\nfor paging to work."
          nullable: true
        previousPageStart:
          type: string
          description: The counter value for the start of the previous search results page.
          nullable: true
          readOnly: true
        pageSize:
          type: string
          description: Requested number of records for the current search results page.
          nullable: true
        pageStart:
          type: string
          description: The counter value for the start of the current search results page.
          nullable: true
        nextPageStart:
          type: string
          description: The counter value for the start of the next search results page.
          nullable: true
          readOnly: true
        totalCount:
          type: integer
          format: int32
        pageStartOffset:
          type: integer
          description: "The page start offset. Since sources are generally 0 based and the view\r\ndefaults to 1 based, our offset defaults to -1."
          format: int32
        format:
          $ref: '#/components/schemas/ViewFormats'
        xhtmlTitle:
          type: string
          nullable: true
          readOnly: true
        resources:
          type: array
          items:
            $ref: '#/components/schemas/UriResourceWithTitle'
          nullable: true
      additionalProperties: false
