openapi: 3.2.0
info:
  title: Student Web Service (SWS) College API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: College
paths:
  /v5/college:
    get:
      tags:
      - College
      summary: Search for colleges that match the supplied parameters
      description: '{

        "DisplayTitle" : "College Search",

        "ews_guid" : "76D0EC71-692F-42A9-959C-3C4EA5D8A1F4",

        "LongDescription" : "Display a filtered list of colleges.

        Can filter by year, quarter, how many future terms to look ahead, and campus short name.",

        "ShortDescription" : "Display a filtered list of colleges",

        "OriginatingSchema" : [ { "source":"swssdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:GradeSubmitter

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        - AccessToken

        For campus short name refer to the campus resource.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.college" ],

        "Synonyms" : []

        }'
      operationId: CollegeSearch
      parameters:
      - name: year
        in: query
        description: 'The 4 digit year.  For example: 2025'
        schema:
          type: string
          default: ''
      - name: quarter
        in: query
        description: 'The 1 digit quarter.  For example: 0=Default, 1=winter, 2=spring, 3=summer, 4=autumn'
        schema:
          type: string
          default: ''
      - name: future_terms
        in: query
        description: Number of future terms to look ahead
        schema:
          type: integer
          format: int32
          default: 0
      - name: campus_short_name
        in: query
        description: Choose Seattle, Bothell, or Tacoma
        schema:
          type: string
          default: ''
      responses:
        '400':
          description: Invalid input
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/CollegeSearchViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/CollegeSearchViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/CollegeSearchViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/CollegeSearchViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/CollegeSearchViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/CollegeSearchViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    CollegeSearchViewModel:
      type: object
      properties:
        Current:
          $ref: '#/components/schemas/CollegeSearchResourceUri'
        Next:
          $ref: '#/components/schemas/CollegeSearchResourceUri'
        Previous:
          $ref: '#/components/schemas/CollegeSearchResourceUri'
        TotalCount:
          type: integer
          format: int32
        Colleges:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CollegeSearchResultViewModel'
          readOnly: true
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"College Search Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.College\"}]\n}"
    CollegeSearchResultViewModel:
      type: object
      properties:
        CampusShortName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [        \n                    { \"source\":\"SWSSDB.sys_tbl_25_campus.branch_name\" }\n                ],\n                \"TechnicalDescription\": \"Campus short name\"\n            }\n            </pre>"
        CollegeAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_abbrev\" }\n                ],\n                \"TechnicalDescription\": \"College abbreviation\"\n            }\n            </pre>"
        CollegeFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"College full name\"\n            }\n            </pre>"
        CollegeFullNameTitleCased:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"College full name title cased\"\n            }\n            </pre>"
        CollegeName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_name\" }\n                ],\n                \"TechnicalDescription\": \"College name\"\n            }\n            </pre>"
        CollegeShortName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_short_nm\" }\n                ],\n                \"TechnicalDescription\": \"Campus short name\"\n            }\n            </pre>"
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_qtr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.last_eff_qtr\" }\n                ],\n                \"TechnicalDescription\": \"Calculated field based on a range of first effective to last effective.\"\n            }\n            </pre>"
        Year:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_yr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.last_eff_yr\" }\n                ],\n                \"TechnicalDescription\": \"Calculated field based on a range of first effective to last effective.\"\n            }\n            </pre>"
          format: int32
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"College Search Result\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.College\"}]\n}"
    CollegeSearchResourceUri:
      type: object
      properties:
        CampusShortName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sys_tbl_25_campus.branch_name\" }\n                ],\n                \"TechnicalDescription\": \"Campus short name\"\n            }\n            </pre>"
        FutureTerms:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"Number of future terms to look ahead\"\n            }\n            </pre>"
          format: int32
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_qtr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.last_eff_qtr\" }\n                ],\n                \"TechnicalDescription\": \"Calculated field based on a range of first effective to last effective.\"\n            }\n            </pre>"
        Year:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_yr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.last_eff_yr\" }\n                ],\n                \"TechnicalDescription\": \"Calculated field based on a range of first effective to last effective.\"\n            }\n            </pre>"
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"College Search Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.College\"}],\n    \"TargetOperationId\" : [\"CollegeSearch\"]\n}"
