openapi: 3.2.0
info:
  title: Student Web Service (SWS) Major Students API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: MajorStudents
paths:
  /v5/majorstudents:
    get:
      tags:
      - MajorStudents
      summary: Search for students that are enrolled in a specific program of study
      description: '{

        "DisplayTitle" : "Major Students Search",

        "ews_guid" : "F19F924A-533A-4049-A340-59C88A502F45",

        "LongDescription" : "Returns a list of students that are enrolled in a specific program of study",

        "ShortDescription" : "list of students that are enrolled in a program of study",

        "OriginatingSchema" : [ { "source":"swssdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        See the DegreeAuditProgram resource for programs of study. See the campus resource for campus codes.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.major" ],

        "Synonyms" : []

        }'
      operationId: GetMajorStudents
      parameters:
      - name: year
        in: query
        description: 'The 4 digit year.  For example: 2025'
        schema:
          type: string
          default: ''
      - name: quarter
        in: query
        description: 'The 1 digit quarter.  For example: 0=Default, 1=winter, 2=spring, 3=summer, 4=autumn'
        schema:
          type: string
          default: ''
      - name: campus
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: degree_level
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: degree_type
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: major_abbreviation
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: pathway
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: page_size
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: page_start
        in: query
        description: ''
        schema:
          type: string
          default: ''
      responses:
        '400':
          description: 'Invalid arg: year | Invalid arg: quarter | Invalid arg: campus | Invalid arg: degree_level | Invalid arg: degree_type | Invalid arg: major_abbreviation | Invalid arg: pathway | Invalid arg: pageSize | Invalid arg: pageStart | Invalid arg: page_start must be >= 0 | Invalid arg: page_size maximum 500'
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/MajorStudentsViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/MajorStudentsViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/MajorStudentsViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/MajorStudentsViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/MajorStudentsViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/MajorStudentsViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    MajorStudentsPersonResourceUri:
      type: object
      properties:
        Href:
          type:
          - string
          - 'null'
        Name:
          type:
          - string
          - 'null'
        RegID:
          type:
          - string
          - 'null'
        Pronouns:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Major Students Person Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.MajorStudents\"}],\n    \"TargetOperationId\" : [\"GetPerson\"]\n}"
    MajorStudentsViewModel:
      type: object
      properties:
        Major:
          $ref: '#/components/schemas/MajorViewModel'
        Students:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/MajorStudentsPersonResourceUri'
        PageStart:
          type:
          - string
          - 'null'
        PageSize:
          type:
          - string
          - 'null'
        TotalCount:
          type: integer
          format: int32
        Current:
          $ref: '#/components/schemas/MajorStudentsResourceUri'
        Previous:
          $ref: '#/components/schemas/MajorStudentsResourceUri'
        Next:
          $ref: '#/components/schemas/MajorStudentsResourceUri'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Major Students Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.MajorStudents\"}]\n}"
    MajorStudentsResourceUri:
      type: object
      properties:
        Href:
          type:
          - string
          - 'null'
        PageStart:
          type:
          - string
          - 'null'
        PageSize:
          type:
          - string
          - 'null'
        Year:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.registration.regis_yr\" },\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_yr\" }\n                ],\n                \"TechnicalDescription\": \"Year\"\n            }\n            </pre>"
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.registration.regis_qtr\" },\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_qtr\" }\n                ],\n                \"TechnicalDescription\": \"Quarter\"\n            }\n            </pre>"
        Campus:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sys_tbl_25_campus.branch_name\" }\n                ],\n                \"TechnicalDescription\": \"Campus name\"\n            }\n            </pre>"
        DegreeLevel:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.student_1_college_major.deg_level\" },\n                    { \"source\":\"SWSSDB.registration_regis_col_major.regis_deg_level\" },\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_deg_level\" }\n                ],\n                \"TechnicalDescription\": \"Degree level\"\n            }\n            </pre>"
        DegreeType:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.student_1_college_major.deg_type\" },\n                    { \"source\":\"SWSSDB.registration_regis_col_major.regis_deg_type\" },\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_deg_type\" }\n                ],\n                \"TechnicalDescription\": \"Degree type\"\n            }\n            </pre>"
        MajorAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Abbreviation\"\n            }\n            </pre>"
        Pathway:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.registration_regis_col_major.regis_pathway\" }\n                    { \"source\":\"SWSSDB.student_1_college_major.pathway\"},\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_pathway\" }\n                ],\n                \"TechnicalDescription\": \"Major pathway\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Major Students Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.MajorStudents\"}],\n    \"TargetOperationId\" : [\"GetMajorStudents\"]\n}"
    MajorViewModel:
      type: object
      properties:
        Abbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Abbreviation\"\n            }\n            </pre>"
        Campus:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sys_tbl_25_campus.branch_name\" }\n                ],\n                \"TechnicalDescription\": \"Campus name\"\n            }\n            </pre>"
        DegreeLevel:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.student_1_college_major.deg_level\" },\n                    { \"source\":\"SWSSDB.registration_regis_col_major.regis_deg_level\" },\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_deg_level\" }\n                ],\n                \"TechnicalDescription\": \"Degree level\"\n            }\n            </pre>"
          format: int32
        DegreeName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_degree.deg_title\" }\n                ],\n                \"TechnicalDescription\": \"Degree name\"\n            }\n            </pre>"
        DegreeType:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.student_1_college_major.deg_type\" },\n                    { \"source\":\"SWSSDB.registration_regis_col_major.regis_deg_type\" },\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_deg_type\" }\n                ],\n                \"TechnicalDescription\": \"Degree type\"\n            }\n            </pre>"
          format: int32
        FullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"Major full name\"\n            }\n            </pre>"
        MajorName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_name\" }\n                ],\n                \"TechnicalDescription\": \"Major name\"\n            }\n            </pre>"
        Pathway:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.registration_regis_col_major.regis_pathway\" },\n                    { \"source\":\"SWSSDB.student_1_college_major.pathway\"},\n                    { \"source\":\"SWSSDB.transcript_tran_col_major.tran_pathway\" }\n                ],\n                \"TechnicalDescription\": \"Major pathway\"\n            }\n            </pre>"
          format: int32
        ShortName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_major_code.major_short_nm\" }\n                ],\n                \"TechnicalDescription\": \"Major short name\"\n            }\n            </pre>"
        CollegeAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_abbrev\" }\n                ],\n                \"TechnicalDescription\": \"College Abbreviation\"\n            }\n            </pre>"
        CollegeFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_coll_code.college_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"College full name\"\n            }\n            </pre>"
        DepartmentCode:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_dept_code.dept_code\" }\n                ],\n                \"TechnicalDescription\": \"Department Code\"\n            }\n            </pre>"
        DepartmentAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_dept_code.dept_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Department Abbreviation\"\n            }\n            </pre>"
        DepartmentFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_dept_code.dept_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"Department Full Name\"\n            }\n            </pre>"
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Expanded Major Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.MajorStudents\"}]\n}"
