openapi: 3.2.0
info:
  title: Student Web Service (SWS) Campus API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: Campus
paths:
  /v5/campus:
    get:
      tags:
      - Campus
      summary: Get available campuses
      description: '{

        "DisplayTitle" : "Campus List",

        "ews_guid" : "317D6605-20FA-4D10-80A0-75C655B489F3",

        "LongDescription" : "Display a list of campuses",

        "ShortDescription" : "Campus list",

        "OriginatingSchema" : [ { "source":"hardcoded" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:GradeSubmitter

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        - AccessToken

        Unlike other search resources, it does not require any query string to return the search result.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.campus" ],

        "Synonyms" : []

        }'
      operationId: CampusSearch
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/CampusSearchViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/CampusSearchViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/CampusSearchViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/CampusSearchViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/CampusSearchViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/CampusSearchViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    CampusResourceUri:
      type: object
      properties:
        CampusShortName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"hardcoded\" }\n                ],\n                \"TechnicalDescription\": \"Abbreviation of campus\"\n            }\n            </pre>"
        CampusFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                   { \"source\":\"hardcoded\" }\n                ],\n                \"TechnicalDescription\": \"Full Name of the Campus\"\n            }\n            </pre>"
        CampusName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                   { \"source\":\"hardcoded\" }\n                ],\n                \"TechnicalDescription\": \"Name of the campus\"\n            }\n            </pre>"
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Campus Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Campus\"}],\n    \"TargetOperationId\" : [\"CampusSearch\"]\n}"
    CampusSearchResourceUri:
      type: object
      properties:
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Campus Search Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Campus\"}],\n    \"TargetOperationId\" : [\"CampusSearch\"]\n}"
    CampusSearchViewModel:
      type: object
      properties:
        Current:
          $ref: '#/components/schemas/CampusSearchResourceUri'
        Next:
          $ref: '#/components/schemas/CampusSearchResourceUri'
        PageSize:
          type:
          - string
          - 'null'
        PageStart:
          type:
          - string
          - 'null'
        Previous:
          $ref: '#/components/schemas/CampusSearchResourceUri'
        TotalCount:
          type: integer
          format: int32
        Campuses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CampusResourceUri'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Campus Search Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Campus\"}]\n}"
