openapi: 3.2.0
info:
  title: Student Web Service (SWS) Curriculum API
  description: Student Web Service (SWS) provides a RESTful API to access and update central student data. Subscribe to http://mailman.u.washington.edu/mailman/listinfo/sws-client-app-dev to get notifications about planned outages, support and the announcement of new features.
  contact:
    name: Enterprise Web Services & Events Team
    url: https://itconnect.uw.edu/service/enterprise-web-services-and-events/
    email: sws-support@uw.edu
  version: v5
servers:
- url: /student
tags:
- name: Curriculum
paths:
  /v5/curriculum:
    get:
      tags:
      - Curriculum
      summary: Search for curriculums that match the supplied parameters
      description: '{

        "DisplayTitle" : "Curriculum Search",

        "ews_guid" : "AC340F89-812E-4FCB-B357-DCCFE65E0059",

        "LongDescription" : "Search for a list of curriculum results that match the supplied parameters",

        "ShortDescription" : "Search for a list of curriculum results",

        "OriginatingSchema" : [ { "source":"swssdb" } ],

        "Notes" : "This resource requires any of the following ASTRA roles:

        - sws:Support

        - sws:GradeSubmitter

        - sws:UnitReader

        This resource supports the following authentication types:

        - X.509 Certificate

        - NetID

        - AccessToken

        You do not need to specify all parameters to return a successful search result. This search resource

        supports different combinations of search parameters to provide different search results.

        For college abbreviations refer to the college resource.

        For department abbreviations refer to the department resource.",

        "Links" : [ "https://metadata.uw.edu/Catalog/ViewItem/Term/studentdata.curriculum" ],

        "Synonyms" : []

        }'
      operationId: CurriculumSearch
      parameters:
      - name: year
        in: query
        description: 'The 4 digit year.  For example: 2025'
        required: true
        schema:
          type: string
          default: ''
      - name: quarter
        in: query
        description: 'The 1 digit quarter.  For example: 0=Default, 1=winter, 2=spring, 3=summer, 4=autumn'
        required: true
        schema:
          type: string
          default: ''
      - name: future_terms
        in: query
        description: Number of future terms to look ahead
        schema:
          type: integer
          format: int32
          default: 0
      - name: department_abbreviation
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: college_abbreviation
        in: query
        description: ''
        schema:
          type: string
          default: ''
      - name: view_unpublished
        in: query
        description: ''
        schema:
          type: string
          default: 'false'
      responses:
        '400':
          description: 'Invalid input | Invalid arg: college abbreviation'
        '200':
          description: OK
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/CurriculumSearchViewModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/CurriculumSearchViewModel'
            text/xml:
              schema:
                $ref: '#/components/schemas/CurriculumSearchViewModel'
            text/plain:
              schema:
                $ref: '#/components/schemas/CurriculumSearchViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/CurriculumSearchViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/CurriculumSearchViewModel'
        '202':
          description: Accepted
        '301':
          description: MovedPermanently
        '302':
          description: Found
        '304':
          description: NotModified
        '401':
          description: Identity '{identity}' is not authorized to access this resource.
        '405':
          description: MethodNotAllowed
        '500':
          description: InternalServerError
        '503':
          description: ServiceUnavailable
components:
  schemas:
    CurriculumResourceUri:
      type: object
      properties:
        Year:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_yr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.last_eff_yr\" }\n                ],\n                \"TechnicalDescription\": \"Year\"\n            }\n            </pre>"
          format: int32
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_course_titles.first_eff_qtr\" },\n                    { \"source\":\"SWSSDB.sr_course_titles.last_eff_qtr\" }\n                ],\n                \"TechnicalDescription\": \"Quarter\"\n            }\n            </pre>"
        CurriculumAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_curric_code.curric_abbr\" }\n                ],\n                \"TechnicalDescription\": \"Curriculum abbreviation\"\n            }\n            </pre>"
        CurriculumName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_curric_code.curric_name\" }\n                ],\n                \"TechnicalDescription\": \"Curriculum name\"\n            }\n            </pre>"
        CurriculumFullName:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"SWSSDB.sr_curric_code.curric_full_nm\" }\n                ],\n                \"TechnicalDescription\": \"Curriculum full name\"\n            }\n            </pre>"
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Expanded Curriculum Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Curriculum\"}],\n    \"TargetOperationId\" : [\"CurriculumSearch\"]\n}"
    CurriculumSearchResourceUri:
      type: object
      properties:
        Year:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
          format: int32
        Quarter:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        DepartmentAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        CollegeAbbreviation:
          type:
          - string
          - 'null'
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
        FutureTerms:
          type: integer
          description: "<pre>\n            {\n                \"OriginatingSchema\" : [\n                    { \"source\":\"url\" }\n                ],\n                \"TechnicalDescription\": \"User supplied value\"\n            }\n            </pre>"
          format: int32
        ViewUnpublished:
          type: boolean
        Href:
          type:
          - string
          - 'null'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Curriculum Search Resource URI\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Curriculum\"}],\n    \"TargetOperationId\" : [\"CurriculumSearch\"]\n}"
    CurriculumSearchViewModel:
      type: object
      properties:
        TotalCount:
          type: integer
          format: int32
        Curricula:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CurriculumResourceUri'
          readOnly: true
        PageSize:
          type:
          - string
          - 'null'
        PageStart:
          type:
          - string
          - 'null'
        Current:
          $ref: '#/components/schemas/CurriculumSearchResourceUri'
        Next:
          $ref: '#/components/schemas/CurriculumSearchResourceUri'
        Previous:
          $ref: '#/components/schemas/CurriculumSearchResourceUri'
      additionalProperties: false
      description: "{\n    \"DisplayTitle\" : \"Curriculum Search Model\",\n    \"TargetSchema\" : [{\"target\" : \"SWS.Curriculum\"}]\n}"
